from sys import argv
script,filename=argv
print(f'we are going to erase{filename}')
print(f'if ypu dont want that.press CTRL-C(^C)')
print('if you do want that.hit RETURN')
input('?')
print('opening the file....')
target=open(filename,'w')
print('truncating the file.goodbye!!')
target.truncate()
print('now im gonna ask you for 3 lines')
line1=input('line 1:')
line2=input('line 2:')
line3=input('line 3:')
print("i'm gonna write these to the file")
target.write(line1)
target.write('\n')
target.write(line2)
target.write('\n')
target.write(line3)
target.write('\n')
print(' and finally we close it')
target.close()
