print("how old are you",end=' ')
age=input()
print("how tall are you",end=' ')
height=input()
print("hoe much do you weigh",end=' ')
weight=input()
print(f"so you are {age} old,{height} tall , you weigh {weight} heavy")
